CREATE TABLE FESTA(
	NOME VARCHAR(32) NOT NULL,
	EDICAO SMALLINT NOT NULL,
	CONSUMACAO REAL,
	TIPO SMALLINT NOT NULL,
	PLAYLIST VARCHAR(128),
	CONSTRAINT PK_FESTA PRIMARY KEY(NOME, EDICAO),
	CONSTRAINT CK_FESTA1 CHECK (EDICAO >= 1),
	CONSTRAINT CK_FESTA2 CHECK (CONSUMACAO >= 0)
);

COMMENT ON COLUMN FESTA.TIPO is '0: HALLOWEEN, 1: FESTA JUNINA';

CREATE TABLE HALLOWEEN(
	FESTA VARCHAR(32) NOT NULL,
	EDICAO SMALLINT NOT NULL,
	CONSTRAINT PK_HALLOWEEN PRIMARY KEY(FESTA, EDICAO),
	CONSTRAINT FK_HALLOWEEN FOREIGN KEY(FESTA, EDICAO) REFERENCES FESTA(NOME, EDICAO)
		ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE FESTA_JUNINA(
	FESTA VARCHAR(32) NOT NULL,
	EDICAO SMALLINT NOT NULL,
	CONSTRAINT PK_JUNINA PRIMARY KEY(FESTA, EDICAO),
	CONSTRAINT FK_JUNINA FOREIGN KEY(FESTA, EDICAO) REFERENCES FESTA(NOME, EDICAO)
		ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE MEMBRO_COMISSAO(
	CPF CHAR(14) NOT NULL,
	EMAIL VARCHAR(48),
	NOME VARCHAR(48) NOT NULL,
	TELEFONE CHAR(15),
	CONSTRAINT PK_MEMBRO PRIMARY KEY(CPF)
);

CREATE TABLE ORGANIZACAO(
	MEMBRO CHAR(14) NOT NULL,
	FESTA VARCHAR(32) NOT NULL,
	EDICAO SMALLINT NOT NULL,
	CONSTRAINT PK_ORGANIZACAO PRIMARY KEY(MEMBRO, FESTA, EDICAO),
	CONSTRAINT FK_ORGANIZACAO FOREIGN KEY(MEMBRO) REFERENCES MEMBRO_COMISSAO(CPF)
		ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE LUGAR(
	CNPJ CHAR(14),
	ENDERECO VARCHAR(256) NOT NULL,
	N_BANHEIROS SMALLINT,
	LOT_MAX INT,
	CAP_BARRACAS SMALLINT,
	CONSTRAINT PK_LUGAR PRIMARY KEY(ENDERECO),
	CONSTRAINT CK_LUGAR CHECK 
		(N_BANHEIROS >= 0 AND
		LOT_MAX>= 0 AND 
		CAP_BARRACAS>= 0)
);

CREATE TABLE ALUGUEL(
	ENDERECO VARCHAR(256) NOT NULL,
	INICIO TIMESTAMP NOT NULL,
	FIM TIMESTAMP NOT NULL,
	FESTA VARCHAR(32) NOT NULL,
	EDICAO SMALLINT NOT NULL,
	VALOR REAL,
	CONSTRAINT PK_ALUGUEL PRIMARY KEY(ENDERECO, INICIO, FIM),
	CONSTRAINT FK_ALUGUEL1 FOREIGN KEY(FESTA, EDICAO) REFERENCES FESTA(NOME, EDICAO)
		ON DELETE CASCADE ON UPDATE CASCADE,
CONSTRAINT FK_ALUGUEL2 FOREIGN KEY(ENDERECO) REFERENCES LUGAR(ENDERECO)
		ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT SK_ALUGUEL UNIQUE(FESTA, EDICAO)
);

CREATE TABLE EQUIPAMENTO(
	NOME VARCHAR(32) NOT NULL,
	DESCRICAO VARCHAR(64),
	QTD_TOTAL SMALLINT NOT NULL,
	QTD_DISPONIVEL SMALLINT,
	CATEGORIA SMALLINT,
	CONSTRAINT PK_EQUIP PRIMARY KEY(NOME),
	CONSTRAINT CK_EQUIP1 CHECK (QTD_TOTAL >= 1),
	CONSTRAINT CK_EQUIP2 CHECK (QTD_DISPONIVEL >= 0 AND QTD_DISPONIVEL <= QTD_TOTAL)
);

COMMENT ON COLUMN EQUIPAMENTO.CATEGORIA is '0: SOM, 1: VIDEO, 2: FOTOGRAFIA, 3: INFRAESTRUTURA, 4: ETC';

CREATE TABLE EMPRESTIMO(
	EQUIPAMENTO VARCHAR(32) NOT NULL,
	FESTA VARCHAR(32) NOT NULL,
	EDICAO SMALLINT NOT NULL,
	DT_EMPRESTIMO DATE,
	DT_DEVOLUCAO DATE,
	QTD SMALLINT,
	CONSTRAINT PK_EMPRESTIMO PRIMARY KEY(FESTA, EDICAO, EQUIPAMENTO),
	CONSTRAINT FK_EMPRESTIMO1 FOREIGN KEY(FESTA, EDICAO) REFERENCES FESTA(NOME, EDICAO)
		ON DELETE CASCADE ON UPDATE CASCADE,	
	CONSTRAINT FK_EMPRESTIMO2 FOREIGN KEY(EQUIPAMENTO) REFERENCES EQUIPAMENTO(NOME)
		ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT CK_EMPRESTIMO CHECK (QTD >= 1)
);

CREATE TABLE EMPRESA(
	CNPJ CHAR(14) NOT NULL,
	NOME_FANTASIA VARCHAR(32),
	TELEFONE CHAR(15),
	CATEGORIA_SERVICO SMALLINT,
	CONSTRAINT PK_EMPRESA PRIMARY KEY(CNPJ)
);

COMMENT ON COLUMN EMPRESA.CATEGORIA_SERVICO is '0: FORNECEDOR, 1: SEGURANCA, 2:LIMPEZA, 3: ATENDENTES, 4: OUTROS';

CREATE TABLE CONTRATO(
	EMPRESA CHAR(14) NOT NULL,
	FESTA VARCHAR(32) NOT NULL,
	EDICAO SMALLINT NOT NULL,
	VALOR REAL,
	CONSTRAINT PK_CONTRATO PRIMARY KEY(EMPRESA, FESTA, EDICAO),
	CONSTRAINT FK_CONTRATO1 FOREIGN KEY(FESTA, EDICAO) REFERENCES FESTA(NOME, EDICAO)
		ON DELETE CASCADE ON UPDATE CASCADE,	
	CONSTRAINT FK_CONTRATO2 FOREIGN KEY(EMPRESA) REFERENCES EMPRESA(CNPJ)
		ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE PRODUTO(
	ID_PRODUTO INT NOT NULL, 
	NOME VARCHAR(32),
	FORNECEDOR CHAR(14),
	FESTA VARCHAR(32) NOT NULL,
	EDICAO SMALLINT NOT NULL,
	CUSTO REAL,
	QTD SMALLINT,
	TIPO SMALLINT,
	CONSTRAINT PK_PRODUTO PRIMARY KEY(ID_PRODUTO),
	CONSTRAINT FK_PRODUTO FOREIGN KEY(FESTA, EDICAO, FORNECEDOR) REFERENCES CONTRATO(FESTA, EDICAO, EMPRESA)
		ON DELETE CASCADE ON UPDATE CASCADE,	
	CONSTRAINT SK_PRODUTO UNIQUE(FESTA, EDICAO, FORNECEDOR, NOME),
CONSTRAINT CK_PRODUTO CHECK (CUSTO >= 0)
);

COMMENT ON COLUMN PRODUTO.TIPO is '0: COMIDA, 1: PRENDA';

CREATE TABLE BARRACA(
	ID_BARRACA INT,
	NUMERO SMALLINT NOT NULL,
	FESTA VARCHAR(32) NOT NULL,
	EDICAO SMALLINT NOT NULL,
	NOME VARCHAR(32),
	DESCRICAO VARCHAR(256),
	TIPO SMALLINT,
	CONSTRAINT PK_BARRACA PRIMARY KEY(ID_BARRACA),
	CONSTRAINT FK_BARRACA FOREIGN KEY(FESTA, EDICAO) REFERENCES FESTA(NOME, EDICAO)
		ON DELETE CASCADE ON UPDATE CASCADE,	
	CONSTRAINT SK_BARRACA UNIQUE (FESTA, EDICAO, NUMERO)
);

COMMENT ON COLUMN FESTA.TIPO is '0: COMIDA, 1: LAZER, 2: RECARGA';

CREATE TABLE RESPONSAVEL_BARRACA(
	MEMBRO CHAR(14) NOT NULL,
	BARRACA INT NOT NULL,
	CONSTRAINT PK_RESPONSAVEL PRIMARY KEY(MEMBRO, BARRACA),
	CONSTRAINT FK_RESPONSAVEL1 FOREIGN KEY(MEMBRO) REFERENCES MEMBRO_COMISSAO(CPF)
		ON DELETE CASCADE ON UPDATE CASCADE,	
	CONSTRAINT FK_RESPONSAVEL2 FOREIGN KEY(BARRACA) REFERENCES BARRACA(ID_BARRACA)
		ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE COMIDA(
	PRODUTO INT NOT NULL,
	PRECO REAL,
	CONSTRAINT PK_COMIDA PRIMARY KEY(PRODUTO),
	CONSTRAINT FK_COMIDA FOREIGN KEY(PRODUTO) REFERENCES PRODUTO(ID_PRODUTO)
		ON DELETE CASCADE ON UPDATE CASCADE,
CONSTRAINT CK_COMIDA CHECK (PRECO > 0)
);

CREATE TABLE VENDA(
	COMIDA INT NOT NULL,
	BARRACA INT NOT NULL,
	CONSTRAINT PK_VENDA PRIMARY KEY(COMIDA, BARRACA),
	CONSTRAINT FK_VENDA1 FOREIGN KEY(COMIDA) REFERENCES COMIDA(PRODUTO)
		ON DELETE CASCADE ON UPDATE CASCADE,	
	CONSTRAINT FK_VENDA2 FOREIGN KEY(BARRACA) REFERENCES BARRACA(ID_BARRACA)
		ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE PRENDA(
	PRODUTO INT NOT NULL,
	PONTUACAO INT,
	CONSTRAINT PK_PRENDA PRIMARY KEY(PRODUTO),
	CONSTRAINT FK_PRENDA FOREIGN KEY(PRODUTO) REFERENCES PRODUTO(ID_PRODUTO)
		ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE LAZER(
	PRECO REAL,
	BARRACA INT NOT NULL,
	CONSTRAINT PK_LAZER PRIMARY KEY(BARRACA),
	CONSTRAINT FK_LAZER FOREIGN KEY(BARRACA) REFERENCES BARRACA(ID_BARRACA)
		ON DELETE CASCADE ON UPDATE CASCADE,
CONSTRAINT CK_LAZER CHECK (PRECO >= 0)
);

CREATE TABLE DISTRIBUICAO(
	PRENDA INT NOT NULL,
	BARRACA INT NOT NULL,
	CONSTRAINT PK_DISTRIBUICAO PRIMARY KEY(PRENDA, BARRACA),
	CONSTRAINT FK_DISTRIBUICAO1 FOREIGN KEY(PRENDA) REFERENCES PRENDA(PRODUTO)
		ON DELETE CASCADE ON UPDATE CASCADE,	
	CONSTRAINT FK_DISTRIBUICAO2 FOREIGN KEY(BARRACA) REFERENCES LAZER(BARRACA)
		ON DELETE CASCADE ON UPDATE CASCADE
);


CREATE TABLE PARTICIPANTE(
	COD_CARTAO INT NOT NULL,
	SALDO REAL,
	FESTA VARCHAR(32) NOT NULL,
	EDICAO SMALLINT NOT NULL,
	CONSTRAINT PK_PARTICIPANTE PRIMARY KEY(COD_CARTAO),
	CONSTRAINT FK_PARTICIPANTE FOREIGN KEY(FESTA, EDICAO) REFERENCES FESTA(NOME, EDICAO)
		ON DELETE CASCADE ON UPDATE CASCADE,
CONSTRAINT CK_PARTICIPANTE CHECK (SALDO >= 0)
);

CREATE TABLE RECARGA(
	PARTICIPANTE INT NOT NULL,
	BARRACA INT NOT NULL,
	HORA TIMESTAMP NOT NULL,
	VALOR REAL NOT NULL,
	CONSTRAINT PK_RECARGA PRIMARY KEY(PARTICIPANTE, BARRACA, HORA),
	CONSTRAINT FK_RECARGA1 FOREIGN KEY(PARTICIPANTE) REFERENCES PARTICIPANTE(COD_CARTAO)
		ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT FK_RECARGA2 FOREIGN KEY(BARRACA) REFERENCES BARRACA(ID_BARRACA)
		ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT CK_RECARGA CHECK (VALOR > 0)
);

CREATE TABLE CONC_ADV(
	ID_CONCURSO INT NOT NULL,
	FESTA VARCHAR(32) NOT NULL,
	EDICAO SMALLINT NOT NULL,
	NOME VARCHAR(32),
	PREMIO INT,
	ITEM VARCHAR(32),
	CONSTRAINT PK_CONC_ADV PRIMARY KEY(ID_CONCURSO),
	CONSTRAINT FK_CONC_ADV1 FOREIGN KEY(FESTA, EDICAO) REFERENCES FESTA_JUNINA(FESTA, EDICAO)
		ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT FK_CONC_ADV2 FOREIGN KEY(PREMIO) REFERENCES PRODUTO(ID_PRODUTO)
		ON DELETE CASCADE ON UPDATE CASCADE,	
	CONSTRAINT FK_CONC_ADV3 FOREIGN KEY(ITEM, FESTA, EDICAO) REFERENCES EMPRESTIMO(EQUIPAMENTO, FESTA, EDICAO)
		ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT SK_CONC_ADV UNIQUE(FESTA, EDICAO, NOME)
);

CREATE TABLE COORD_ADV(
	COORDENADOR CHAR(14) NOT NULL,
	CONCURSO INT NOT NULL,
	CONSTRAINT PK_COORD_ADV PRIMARY KEY(COORDENADOR, CONCURSO),
	CONSTRAINT FK_COORD_ADV1 FOREIGN KEY(CONCURSO) REFERENCES CONC_ADV(ID_CONCURSO)
		ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT FK_COORD_ADV2 FOREIGN KEY(COORDENADOR) REFERENCES MEMBRO_COMISSAO(CPF)
		ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE CONC_COMIDA(
	ID_CONCURSO INT NOT NULL,
	FESTA VARCHAR(32) NOT NULL,
	EDICAO SMALLINT NOT NULL,
	NOME VARCHAR(32),
	PREMIO INT,
	COMIDA INT,
	CONSTRAINT PK_CONC_COMIDA PRIMARY KEY(ID_CONCURSO),
	CONSTRAINT FK_CONC_COMIDA1 FOREIGN KEY(FESTA, EDICAO) REFERENCES FESTA_JUNINA(FESTA, EDICAO)
		ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT FK_CONC_COMIDA2 FOREIGN KEY(PREMIO) REFERENCES PRODUTO(ID_PRODUTO)
		ON DELETE CASCADE ON UPDATE CASCADE,	
	CONSTRAINT FK_CONC_COMIDA3 FOREIGN KEY(COMIDA) REFERENCES COMIDA(PRODUTO)
		ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT SK_CONC_COMIDA UNIQUE(FESTA, EDICAO, NOME)
);

CREATE TABLE COORD_COMIDA(
	COORDENADOR CHAR(14) NOT NULL,
	CONCURSO INT NOT NULL,
	CONSTRAINT PK_COORD_COMIDA PRIMARY KEY(COORDENADOR, CONCURSO),
	CONSTRAINT FK_COORD_COMIDA1 FOREIGN KEY(CONCURSO) REFERENCES CONC_COMIDA(ID_CONCURSO)
		ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT FK_COORD_COMIDA2 FOREIGN KEY(COORDENADOR) REFERENCES MEMBRO_COMISSAO(CPF)
		ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE TABLE CONC_FANTASIA(
	ID_CONCURSO INT NOT NULL,
	FESTA VARCHAR(32) NOT NULL,
	EDICAO SMALLINT NOT NULL,
	NOME VARCHAR(32),
	PREMIO INT,
	CONSTRAINT PK_CONC_FANTASIA PRIMARY KEY(ID_CONCURSO),
	CONSTRAINT FK_CONC_FANTASIA1 FOREIGN KEY(FESTA, EDICAO) REFERENCES HALLOWEEN(FESTA, EDICAO)
		ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT FK_CONC_FANTASIA2 FOREIGN KEY(PREMIO) REFERENCES PRODUTO(ID_PRODUTO)
		ON DELETE CASCADE ON UPDATE CASCADE,	
	CONSTRAINT SK_CONC_FANTASIA UNIQUE(FESTA, EDICAO, NOME)
);

CREATE TABLE COORD_FANTASIA(
	COORDENADOR CHAR(14) NOT NULL,
	CONCURSO INT NOT NULL,
	CONSTRAINT PK_COORD_FANTASIA PRIMARY KEY(COORDENADOR, CONCURSO),
	CONSTRAINT FK_COORD_FANTASIA1 FOREIGN KEY(CONCURSO) REFERENCES CONC_FANTASIA(ID_CONCURSO)
		ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT FK_COORD_COORD_FANTASIA2 FOREIGN KEY(COORDENADOR) REFERENCES MEMBRO_COMISSAO(CPF)
		ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE ALUGUEL_FANTASIA(
	EMPRESA CHAR(14) NOT NULL,
	FESTA VARCHAR(32) NOT NULL,
	EDICAO SMALLINT NOT NULL,
	CONCURSO INT NOT NULL,
	FANTASIAS INT,
	CONSTRAINT PK_ALUGUEL_FANTASIA PRIMARY KEY(EMPRESA, FESTA, EDICAO, CONCURSO),
	CONSTRAINT FK_ALUGUEL_FANTASIA1 FOREIGN KEY(EMPRESA, FESTA, EDICAO) REFERENCES CONTRATO(EMPRESA, FESTA, EDICAO)
		ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT FK_ALUGUEL_FANTASIA2 FOREIGN KEY(CONCURSO) REFERENCES CONC_FANTASIA(ID_CONCURSO)
		ON DELETE CASCADE ON UPDATE CASCADE
);
